In [62]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split

In [63]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [64]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [65]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [66]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [67]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [69]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [70]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [71]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 1 , verbose = 1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5833 - loss: 0.6929 - val_accuracy: 0.7500 - val_loss: 0.6387
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6884 - val_accuracy: 0.7500 - val_loss: 0.6355
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6859 - val_accuracy: 0.7500 - val_loss: 0.6330
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5833 - loss: 0.6828 - val_accuracy: 0.7500 - val_loss: 0.6304
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6785 - val_accuracy: 0.7500 - val_loss: 0.6277
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6756 - val_accuracy: 0.7500 - val_loss: 0.6252
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6727 - val_accuracy: 0.7500 - val_loss: 0.6224
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.6686 - val_accuracy: 0.7500 - val_loss: 0.6201
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6673 - val_accuracy: 0.7500 - val_loss: 0.6172
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.6619 - val_accuracy: 0.7500 - val_loss: 0.6145
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.6580 - val_accuracy: 0.7500 - val_loss: 0.6121
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6667 - loss: 0.6546 - val_accuracy: 0.7500 - val_loss: 0.6092
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6667 - loss: 0.6496 - val_accuracy: 0.7500 - val_loss: 0.6062
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6667 - loss: 0.6435 - val_accuracy: 0.7500 - val_loss: 0.6033
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6667 - loss: 0.6376 - val_accuracy: 0.7500 - val_loss: 0.6003
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6667 - loss: 0.6315 - val_accuracy: 0.7500 - val_loss: 0.5972
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6249 - val_accuracy: 0.7500 - val_loss: 0.5943
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6212 - val_accuracy: 0.7500 - val_loss: 0.5919
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6164 - val_accuracy: 0.7500 - val_loss: 0.5906
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6128 - val_accuracy: 0.7500 - val_loss: 0.5888
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6110 - val_accuracy: 0.7500 - val_loss: 0.5867
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6082 - val_accuracy: 0.7500 - val_loss: 0.5850
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6070 - val_accuracy: 0.7500 - val_loss: 0.5833
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6034 - val_accuracy: 0.7500 - val_loss: 0.5807
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.6033 - val_accuracy: 0.7500 - val_loss: 0.5794
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5989 - val_accuracy: 0.7500 - val_loss: 0.5766
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5980 - val_accuracy: 0.7500 - val_loss: 0.5748
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5948 - val_accuracy: 0.7500 - val_loss: 0.5720
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5931 - val_accuracy: 0.7500 - val_loss: 0.5702
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5911 - val_accuracy: 0.7500 - val_loss: 0.5672
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5886 - val_accuracy: 0.7500 - val_loss: 0.5651
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5857 - val_accuracy: 0.7500 - val_loss: 0.5631
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5838 - val_accuracy: 0.7500 - val_loss: 0.5611
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5823 - val_accuracy: 0.7500 - val_loss: 0.5583
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5806 - val_accuracy: 0.7500 - val_loss: 0.5570
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5777 - val_accuracy: 0.7500 - val_loss: 0.5544
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5755 - val_accuracy: 0.7500 - val_loss: 0.5524
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5734 - val_accuracy: 0.7500 - val_loss: 0.5496
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5707 - val_accuracy: 0.7500 - val_loss: 0.5479
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5695 - val_accuracy: 0.7500 - val_loss: 0.5460
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5665 - val_accuracy: 0.7500 - val_loss: 0.5438
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5646 - val_accuracy: 0.7500 - val_loss: 0.5415
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5623 - val_accuracy: 0.7500 - val_loss: 0.5396
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5613 - val_accuracy: 0.7500 - val_loss: 0.5382
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5579 - val_accuracy: 0.7500 - val_loss: 0.5353
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5562 - val_accuracy: 0.7500 - val_loss: 0.5330
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5538 - val_accuracy: 0.7500 - val_loss: 0.5309
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5520 - val_accuracy: 0.7500 - val_loss: 0.5285
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5501 - val_accuracy: 0.7500 - val_loss: 0.5261
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5475 - val_accuracy: 0.7500 - val_loss: 0.5244
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5454 - val_accuracy: 0.7500 - val_loss: 0.5225
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5446 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5414 - val_accuracy: 0.7500 - val_loss: 0.5181
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7500 - loss: 0.5398 - val_accuracy: 0.7500 - val_loss: 0.5166
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5373 - val_accuracy: 0.7500 - val_loss: 0.5139
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5362 - val_accuracy: 0.7500 - val_loss: 0.5109
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5343 - val_accuracy: 0.7500 - val_loss: 0.5105
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.5337 - val_accuracy: 0.7500 - val_loss: 0.5065
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5291 - val_accuracy: 0.7500 - val_loss: 0.5054
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5276 - val_accuracy: 0.7500 - val_loss: 0.5036
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5250 - val_accuracy: 0.7500 - val_loss: 0.5009
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5230 - val_accuracy: 0.7500 - val_loss: 0.4991
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5209 - val_accuracy: 0.7500 - val_loss: 0.4963
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5187 - val_accuracy: 0.7500 - val_loss: 0.4946
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.5169 - val_accuracy: 0.7500 - val_loss: 0.4930
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.5146 - val_accuracy: 0.7500 - val_loss: 0.4905
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8333 - loss: 0.5127 - val_accuracy: 0.7500 - val_loss: 0.4882
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.5108 - val_accuracy: 0.7500 - val_loss: 0.4859
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5087 - val_accuracy: 0.7500 - val_loss: 0.4837
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5065 - val_accuracy: 0.7500 - val_loss: 0.4812
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.5044 - val_accuracy: 0.7500 - val_loss: 0.4799
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.5024 - val_accuracy: 0.7500 - val_loss: 0.4775
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5007 - val_accuracy: 0.7500 - val_loss: 0.4750
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4984 - val_accuracy: 0.7500 - val_loss: 0.4733
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.4966 - val_accuracy: 0.7500 - val_loss: 0.4710
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.4947 - val_accuracy: 0.7500 - val_loss: 0.4686
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4926 - val_accuracy: 0.7500 - val_loss: 0.4668
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4906 - val_accuracy: 0.7500 - val_loss: 0.4648
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4886 - val_accuracy: 0.7500 - val_loss: 0.4635
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4882 - val_accuracy: 0.7500 - val_loss: 0.4600
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4845 - val_accuracy: 0.7500 - val_loss: 0.4589
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4830 - val_accuracy: 0.7500 - val_loss: 0.4575
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4808 - val_accuracy: 0.7500 - val_loss: 0.4558
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4794 - val_accuracy: 0.7500 - val_loss: 0.4525
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4775 - val_accuracy: 0.7500 - val_loss: 0.4509
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4751 - val_accuracy: 0.7500 - val_loss: 0.4491
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4731 - val_accuracy: 0.7500 - val_loss: 0.4474
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.4714 - val_accuracy: 0.7500 - val_loss: 0.4453
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.4697 - val_accuracy: 0.7500 - val_loss: 0.4436
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4677 - val_accuracy: 0.7500 - val_loss: 0.4420
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4660 - val_accuracy: 0.7500 - val_loss: 0.4393
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4637 - val_accuracy: 0.7500 - val_loss: 0.4375
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4631 - val_accuracy: 0.7500 - val_loss: 0.4346
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4612 - val_accuracy: 0.7500 - val_loss: 0.4323
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4588 - val_accuracy: 0.7500 - val_loss: 0.4322
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4565 - val_accuracy: 0.7500 - val_loss: 0.4297
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4546 - val_accuracy: 0.7500 - val_loss: 0.4286
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4525 - val_accuracy: 0.7500 - val_loss: 0.4265
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4507 - val_accuracy: 0.7500 - val_loss: 0.4245
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.4514 - val_accuracy: 0.7500 - val_loss: 0.4211

In [72]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

In [73]:
X_train_tensor = torch.tensor(
    X_train.values, dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test.values, dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train.values, dtype=torch.float32
).reshape(-1, 1)

y_test_tensor = torch.tensor(
    y_test.values, dtype=torch.float32
).reshape(-1, 1)

In [74]:
train_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor
)

train_loader = DataLoader(
    train_dataset,
    batch_size=1,
    shuffle=True
)

In [75]:
class Model(nn.Module):

    def __init__(self, input_size):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_size, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x)


model = Model(X_train.shape[1])

In [76]:
criterion = nn.BCELoss()

In [77]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

In [78]:
epochs = 100

for epoch in range(epochs):

    model.train()

    for X_batch, y_batch in train_loader:

        # Forward pass
        predictions = model(X_batch)

        # Calculate loss
        loss = criterion(predictions, y_batch)

        # Clear previous gradients
        optimizer.zero_grad()

        # Backpropagation
        loss.backward()

        # Update weights
        optimizer.step()

In [79]:
    model.eval()

    with torch.no_grad():

        test_predictions = model(X_test_tensor)

        val_loss = criterion(
            test_predictions,
            y_test_tensor
        )

        predicted_classes = (
            test_predictions >= 0.5
        ).float()

        accuracy = (
            predicted_classes == y_test_tensor
        ).float().mean()


    print(
        f"Epoch [{epoch+1}/{epochs}] "
        f"Loss: {loss.item():.4f} "
        f"Val Loss: {val_loss.item():.4f} "
        f"Val Accuracy: {accuracy.item():.4f}"
    )

Epoch [100/100] Loss: 0.5060 Val Loss: 0.5700 Val Accuracy: 1.0000

In [80]:
from tensorflow.keras import optimizers

In [81]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)